### ISSUE TITLE
Using version 2.2.0 results in an error when querying SCs

### ISSUE THREAD

**Issue by damienen** [multiversx/mx-sdk-js-network-providers#52]
Seems like because of the update of axios to a new version, the tests (internal tests from the library) that use jest return an error when being used in a project:

TypeError: axios_1.default.post is not a function

A related post: https://github.com/facebook/create-react-app/discussions/12823

**Comment by andreibancioiu** [comment]
Thank you :pray: 

Also reproduced here: https://t.me/MultiversXDevelopers/121486

**Comment by andreibancioiu** [comment]
Issue manifests when used in conjunction with older versions `sdk-dapp`, which referenced an older `axios` (before `v1`).

Normally, the issue should be resolved by:
 - https://github.com/multiversx/mx-sdk-dapp/blob/main/CHANGELOG.md#v2250---2023-12-14
 - https://github.com/multiversx/mx-sdk-dapp/pull/989

Further testing is necessary to confirm the fix, though.

**Comment by andreibancioiu** [comment]
Update: should be fixed by https://github.com/multiversx/mx-sdk-dapp/pull/992.

**Comment by CiprianDraghici** [comment]
@damienen could you check sdk-app@2.25.2 ? Let me know if your error still persist.

cc @andreibancioiu

**Comment by damienen** [comment]
Yes, I can confirm it is still happening when using these packages:
    "@multiversx/sdk-core": "12.17.0",
    "@multiversx/sdk-dapp": "2.25.2",
    "@multiversx/sdk-native-auth-client": "1.0.6",
    "@multiversx/sdk-network-providers": "2.2.0",

**Comment by andreibancioiu** [comment]
Additional step to fix this is attempted here: https://github.com/multiversx/mx-sdk-js-network-providers/pull/53.

**Comment by andreibancioiu** [comment]
Also reported here: https://t.me/MultiversXDevelopers/122488

**Comment by andreibancioiu** [comment]
Possibly related to: https://stackoverflow.com/questions/76888080/react-app-throwing-axios-1-default-post-is-not-a-function-error

**Comment by icegriffinguru** [comment]
> Possibly related to: https://stackoverflow.com/questions/76888080/react-app-throwing-axios-1-default-post-is-not-a-function-error

This resolved the issue. :pray:

**Comment by andreibancioiu** [comment]
Related: https://github.com/multiversx/mx-sdk-dapp/issues/999.

**Comment by danielailie** [comment]
I'll close this issue as it is already a fix for it as mention in the above comment
